packages:
  - packages/@firmachain/*
  - packages/*

catalog:
  typescript: ^5.8.3
  '@types/node': ^22.10.8
  eslint: ^9.30.1
  prettier: ^3.6.2
  jsdom: ^26.1.0
  vite: ^6.3.5
  vite-plugin-dts: ^4.5.4
  vitest: ^3.1.3
  vitest-mock-extended: ^3.1.0
  # Core package dependencies
  tsup: ^7.2.0
  zod: ^3.22.0
  # Testing dependencies
  '@types/jest': ^29.5.0
  jest: ^29.5.0
  ts-jest: ^29.1.0
  # Linting dependencies
  '@typescript-eslint/eslint-plugin': ^8.0.0
  '@typescript-eslint/parser': ^8.0.0
  # Server dependencies
  express: ^4.19.2
  ws: ^8.17.0
  cors: ^2.8.5
  helmet: ^7.1.0
  dotenv: ^16.4.5
  winston: ^3.13.0
  sqlite3: ^5.1.7
  better-sqlite3: ^11.1.2
  node-forge: ^1.3.1
  nanoid: ^5.0.7
  multer: ^1.4.5-lts.1
  express-rate-limit: ^7.2.0
  # Server dev dependencies
  '@types/express': ^4.17.21
  '@types/ws': ^8.5.10
  '@types/cors': ^2.8.17
  '@types/node-forge': ^1.3.11
  '@types/multer': ^1.4.11
  '@types/better-sqlite3': ^7.6.11
  tsx: ^4.7.1

catalogs:
  frontend:
    react: ^19.1.0
    react-dom: ^19.1.0
    '@types/react': ^19.0.7
    '@types/react-dom': ^19.0.3
    tailwindcss: ^4.1.11
    '@tailwindcss/postcss': ^4.1.11
    autoprefixer: ^10.4.20
    postcss: ^8.5.3
    '@testing-library/react': ^16.3.0
    '@testing-library/jest-dom': ^6.6.3
    storybook: ^8.6.14
    '@storybook/addon-essentials': ^8.6.14
    '@storybook/addon-interactions': ^8.6.14
    '@storybook/addon-links': ^8.6.14
    '@storybook/blocks': ^8.6.14
    '@storybook/react': ^8.6.14
    '@storybook/react-vite': ^8.6.14
    '@storybook/test': ^8.6.14
    '@vitejs/plugin-react': ^4.6.0
 
